language: php
php: [7.0, 7.1, 7.2, nightly ]
sudo: false

env:
  global:
    - VERSION=$(echo $TRAVIS_TAG | cut -c 2-10)

install:
- composer install --no-interaction --prefer-dist -o

jobs:
  include:
    - stage: Test
      script:
        - bin/phpunit --no-coverage

    - stage: Lint
      php: 7.1
      script: ./tools/phpstan analyse src tests --level 2 --configuration phpstan.neon
      before_script:
        - wget https://phar.io/releases/phive.phar
        - wget https://phar.io/releases/phive.phar.asc
        - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
        - gpg --verify phive.phar.asc phive.phar
        - php phive.phar install --trust-gpg-keys 8E730BA25823D8B5

    - stage: Coverage
      php: 7.1
      script:
        - bin/phpunit
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

  allow_failures:
    - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  irc: irc.freenode.org#phpdocumentor
  slack:
    secure: fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg=
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
